GearAnswer/urls.py
#coding:utf-8
#GearAnswer/urls.py
from django.conf.urls import patterns, include, url
from  GearAnswer import views
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', views.home_view),
    url(r'^ajax/nav/(\d*?)/$', views.nav_view),
    
    url(r'^login/$', views.login_view),
    url(r'^logout/$', views.logout_view),
    url(r'^register/$', views.register_view),
    url(r'^input/$', views.building_view),
    
    url(r'^node/(\w*?)/$', views.node_view),
    url(r'^node/(\w*?)/input/$', views.update_topic_view),

    url(r'^gear/(\d)/profile/$', views.user_profile_view),
    url(r'^gear/(\d)/profile/edit/$', views.user_profile_edit_view),    
    url(r'^gear/(\d)/profile/messages/$', views.messages_view),
    url(r'^myaccount/$', views.building_view),
    url(r'^myaccount/favorites/$', views.building_view),

    
    url(r'^articles/(\d*?)/$', views.read_view),
    url(r'^articles/(\d*?)/reply/$', views.reply_view),
    url(r'^random/$', views.random_view),
    
    url(r'^ajax/topic/star/$', views.topic_star_view),
    url(r'^ajax/topic/useful/$', views.topic_useful_view),
    url(r'^ajax/topic/useless/$', views.topic_useless_view),
    
    url(r'^test/$', views.test_view),
    
    
    
    
    # Examples:
    # url(r'^$', 'gamegear.views.home', name='home'),
    # url(r'^gamegear/', include('gamegear.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

GearArt/urls.py
#coding:utf-8
#urls.py of GameArt
from django.conf.urls import patterns, include, url
import views
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.home),
    url(r'^test/$', views.test),
    # Examples:
    # url(r'^$', 'gamegear.views.home', name='home'),
    # url(r'^gamegear/', include('gamegear.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

gamegear/urls.py
#coding:utf-8
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import GearAnswer
admin.autodiscover()

#import xadmin
#xadmin.autodiscover()
# version模块自动注册需要版本控制的 Model
#from xadmin.plugins import xversion
#xversion.register_models()

urlpatterns = patterns('',
    #url(r'xadmin/', include(xadmin.site.urls)),
    
    # Examples:
    # url(r'^$', 'gamegear.views.home', name='home'),
    # url(r'^gamegear/', include('gamegear.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('GearAnswer.urls')),
)

GearAnswer/models.py
#!/usr/bin/evn python
#coding:utf-8
#GearAnswer/models.py - models file
#by winkidney - 2014年6月18日

from django.db import models
from django.utils.translation import ugettext_lazy as _
import logging


#from django.core.exceptions import  ObjectDoesNotExist
from UCenter.models import User,Message
from GearAnswer.config import *

EDITOR_TYPES = (
    ('md', _(u'markdown editor')),
    ('ue', _(u'ueditor')),
)

logger = logging.getLogger(__name__)


        
class Node(models.Model):
    
    """Topic Node ,the same as topic Type"""
    class Meta:
        verbose_name_plural = _(u'topic node')
        verbose_name = _(u'topic node ')
      
    name = models.CharField(blank=False, unique=True, 
                            max_length=100, 
                            verbose_name=_(u'node name'))
    create_at = models.DateTimeField(auto_now_add=True, verbose_name=_(u'create at'))
    avatar = models.ImageField(blank=True,
                               upload_to='nodes/', 
                               verbose_name=_(u'node avatar'))
    description = models.TextField(blank=True,
                                   verbose_name=_(u'node description'))
    help_text = models.TextField(blank=True,
                                 verbose_name=_(u"node help text"))
    topic_count = models.IntegerField(blank=False,
                                  default=0, verbose_name=_(u'topic count'))
    parent = models.ForeignKey('Node', 
                               default=0, 
                               blank=False, verbose_name=_(u"parent-node"))
    
    def __unicode__(self):
        
        return self.name
    
    def get_avatar_url(self):
        
        return self.avatar.url
    
    def get_abs_url(self):
        return u"%snode/%s/" % (ANSWER_ROOT, self.name)

class Tag(models.Model):
    
    """Topic tag.Repution is needed for add new tag."""
    
    class Meta:
        verbose_name_plural = _(u'question tag manager')
        verbose_name = _(u'question tag manager')
    
    name = models.CharField(max_length=100, blank=False, verbose_name=_(u'tag name'))
    topic_count = models.IntegerField(blank=False, verbose_name=_(u'question count'))
    
    
    def get_abs_url(self):
        return u"%stags/%s/" % (ANSWER_ROOT, self.name)
    
    def __unicode__(self):
        
        return self.name
    

    
class Topic(models.Model):
    
    """Topic that contains enough info"""
    
    class Meta:
        verbose_name_plural = _(u"topics")
        verbose_name = _(u"topic")
        get_latest_by = "-create_at"
        ordering = ['-update_at']
        
    title = models.CharField(max_length=250, blank=False, 
                             db_index=True,
                             verbose_name=_(u'question title'))
    
    content = models.TextField(blank=True, verbose_name=_(u'topic content'))
    is_question = models.BooleanField(blank=False, default=False, verbose_name=_(u'If it is a question topic'))
    work_out = models.BooleanField(blank=False, default=False, verbose_name=_(u'if the question worked out'))
    editor = models.CharField(max_length=5,
                              blank=False,
                              default='md',
                              choices=EDITOR_TYPES,verbose_name=_(u'topic type')
                              )
    author = models.ForeignKey(User, db_index=True,blank=False, verbose_name=_(u'topic author'))
    reply_count = models.IntegerField(blank=False, default=0, verbose_name=_(u'reply count'))
    
    create_at = models.DateTimeField(auto_now_add=True, verbose_name=_(u'create at'))
    update_at = models.DateTimeField(auto_now=True, verbose_name=_(u'updated at'))
    last_reply_id = models.CharField(max_length=15, blank=True, default='0',
                                     verbose_name=_(u"last reply's id"))
    
    
    useful = models.IntegerField(blank=False, default=0, verbose_name=_(u'useful'))
    #todo : 有更好的设计么？
    useful_uids = models.CharField(max_length=UIDS_RESERVE_LENGTH,
                                   blank=True, 
                                   verbose_name=_(u"uids that mark this topic useful."))
    stars = models.IntegerField(blank=False, default=0, verbose_name=_(u'stared count'))
    
    
    useless = models.IntegerField(blank=False, default=0, verbose_name=_(u'useless'))
    #todo : 有更好的设计么？
    useless_uids = models.CharField(max_length=UIDS_RESERVE_LENGTH,
                                   blank=True, 
                                   verbose_name=_(u"uids that mark this topic useful."))
    view_times = models.IntegerField(blank=False, default=0, verbose_name=_(u'view times'))
    
    #answers = models.ManyToManyField(Answer, blank=True, verbose_name=_(u'response to the topic'))
    tags = models.ManyToManyField(Tag, blank=True, verbose_name=_(u'topic tags'))
    node = models.ForeignKey(Node, blank=False, verbose_name=_(u'topic node'))
    
    @property
    def last_reply(self):
        if self.last_reply_id != '0':
            try:
                return Reply.objects.get(id=self.last_reply_id)
            except:
                return None
        else:
            return None
    
    def get_abs_url(self):
        return u"%sarticles/%s/" % (ANSWER_ROOT, self.id)
    
    def __unicode__(self):
        
        return self.title
    
    def _check_digit_input(self, value):
        "check if the input value is digit.Return value if True."
        if not isinstance(value, (int,str,unicode)):
            raise TypeError,"value [%s] must be an int/str/unicode type object" % value
        value = str(value)
        if not value.isdigit():
            raise TypeError,'value [%s] must be digit.' % value
        return value
    
    def _in_field(self, field_value, uid):
        """
            Check if the given uid in the strings(such as useful_uids string),
            return True or false
        """
        uid = self._check_digit_input(uid)
        uids = field_value.split('_')
        if uid in uids:
            return True
        else:
            return False
        
    def _insert_uid(self, field,  uid):
        """
            Insert a uid into given field.
            it will check if the uid in uidlist,if true,it will not insert.
            Return True if succeed,False if the uid existed.
        """
        field_value = self.__getattribute__(field)
        uid = self._check_digit_input(uid)
        if self._in_field(field_value, uid):
            logger.info("uid [%s] has already in field [%s], will not insert." \
                        % (uid, field))
            return False
        uids = field_value.split('_')
        while len(field_value) > UIDS_MAX_LENGTH:
            uids = field_value.split('_')
            uids.pop(0)
            field_value = '_'.join(uids)
        uids.append(uid)
        self.__setattr__(field,'_'.join(uids))
        logger.info("uid [%s] instered to field [%s]" % (uid, field))
        return True
    
    def insert_useful_uid(self, uid):
        "Note:This method will not save data to database!"
        return self._insert_uid('useful_uids', uid)
    
    def insert_useless_uid(self, uid):
        "Note:This method will not save data to database!"
        return self._insert_uid('useless_uids', uid)
        


class Reply(models.Model):
    
    """Answer for Question"""
    
    class Meta:
        verbose_name_plural = _(u"replys")
        verbose_name = _(u"reply")
        get_latest_by = "-create_at"
        ordering = ['create_at']
    
    editor = models.CharField(max_length=5,
                              blank=False,
                              default='md',
                              choices=EDITOR_TYPES,verbose_name=_(u'editor')
                              )    
    content = models.TextField(blank=False, verbose_name=_(u'reply content'))
    author = models.ForeignKey(User, blank=False, 
                               db_index=True,
                               verbose_name=_(u'reply author'))
    is_best = models.BooleanField(default=False, verbose_name=_(u'is right answer'))
    useful = models.IntegerField(blank=False, default=0, verbose_name=_(u'useful'))
    useless = models.IntegerField(blank=False, default=0, verbose_name=_(u'useless'))
    
    topic = models.ForeignKey(Topic,blank=False,verbose_name=_(u'topic'))
    
    create_at = models.DateTimeField(auto_now_add=True, verbose_name=_(u'create at'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_(u'updated at'))
    
    def __unicode__(self):
        
        return u'%s - %s' %(self.id, self.topic.title)


class UserProfile(models.Model):
    
    """Question Node ,the same topic Type"""
    class Meta:
        verbose_name_plural = _(u'users profile')
        verbose_name = _(u'user profile ')
        
    user = models.OneToOneField(User, blank=False, verbose_name="profile owner")
    fav_topics = models.ManyToManyField(Topic,
                                       blank=True, 
                                verbose_name=_(u"user's favorite's nodes count") )
    fav_nodes = models.ManyToManyField(Node,
                                      blank=True, 
                                      verbose_name=_(u"user's favorite nodes's count")) 
    fav_users = models.ManyToManyField(User,related_name="fav_user",
                                      blank=True,
                                      verbose_name=_(u"user's caring-user count"))
    
    gears = models.IntegerField(blank=False, default=DEFAULT_GEARS, verbose_name=_(u'gears'))
    reputation = models.IntegerField(blank=False, default=0, 
                                     verbose_name=_(u"reputation in GameGear"))
    
    def __unicode__(self):
        return "%s %s" % (self.user.id, self.user)
    
    @property
    def unread_msg_count(self):
        #todo : add msg_get function
        return 0



class Nav(models.Model):
    
    """Nav tabs from Tag,The data to generate nav menu"""

GearAnswer/forms.py
# coding:utf-8
# GearAnswer/forms.py - forms file of the app
# by winkidney - ver0.1 - 2014.05.20
 
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate
from django.forms.util import ErrorList
import uuid

from UCenter.apis import create_user
from UCenter.apis import user_exist,email_exist

from GearAnswer.apis import update_avatar,update_node
from GearAnswer.models import EDITOR_TYPES

class CleanErrorList(ErrorList):
    def __unicode__(self):
        if not self:
            return u''
        return u'%s' % ''.join('%s' % e for e in self)
    
def clean_err_form(form_obj, *args, **kwargs):
    return form_obj(*args, error_class=CleanErrorList, **kwargs)

class LoginForm(forms.Form):
    username = forms.CharField(max_length=250, required=True)
    password = forms.CharField(max_length=20, required=True)
    


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=250,required=True)
    password1 = forms.CharField(max_length=20, required=True)
    password2 = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(required=True)
    
    def check_value(self):
        # Check that the two password entries match
        if user_exist(self.cleaned_data.get("username")):
            self.errors['username'] = _(u'Username existed!')
            return False
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            self.errors['password2'] = _(u'Tow password inputs are different!')
            return False
        if email_exist(self.cleaned_data.get("email")):
            self.errors['email'] = _(u'Email existed!')
            return False
        return True
        
class NewTopicForm(forms.Form):
    """Because of the auto-tag function,
       the tag field now does not exist.
    """
    title = forms.CharField(required=True, max_length=250)
    editor = forms.ChoiceField(required=True,choices=EDITOR_TYPES)
    #todo : add user tag edit function
    tags = forms.CharField(required=False,)
    content_md = forms.CharField(required=False)
    content_ue = forms.CharField(required=False)
    #tag = forms.CharField(required=False)
    


        
class UserProfileForm(forms.Form):
    avatar = forms.ImageField(required=False)
    #username = forms.CharField(max_length=250, required=True)
    description = forms.CharField(max_length=250, required=False)
    website = forms.URLField(required=False)
    good_at = forms.CharField(required=False)
    interests = forms.CharField(required=False)
        
class ReplyFrom(forms.Form):
    "You must run check_value method to ensure the data is valid"
    
    reply_to = forms.CharField(required=False, max_length=10)
    editor = forms.ChoiceField(required=True,choices=EDITOR_TYPES)
    comment_md = forms.CharField(required=False)
    comment_ue = forms.CharField(required=False)
    
    def check_value(self):
        if self.cleaned_data.get('comment_%s' \
                                 % self.cleaned_data.get('editor')):
            return True
        return False

GearAnswer/templates/gearanswer/edit_user_profile.html
{% extends "gearanswer/base.html" %}
{% block title %}修改用户信息 | {{ site_name }}{% endblock %}
{% block left_box %}
                            <div class="left-box gray-bg reply-box radius-3 light-black-box-shadow ">
                                <div class="left-cell gray-text ">
                                    <strong>
                                        <a href="{{ answer_url }}" >{{ site_name }}</a>
                                        &gt; 
                                        修改个人信息
                                    </strong>
                                </div><!--end a left-cell-->

                                <div class="left-cell font-11px">
                                    <form id="reply-to" action="" method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class=" padding-bottom-5">
                                            <label class="width-8 block" >[头像]<span class="error margin-l-10">{% if user_profile_form.errors.avatar %}{{ user_profile_form.errors.avatar }}{% endif %}</span></label>
                                        {% if uinfo_dict.avatar %}
                                            <img class="user-avatar" src="{{ uinfo_dict.avatar }}"><br>
                                        {% else %}
                                            <img class="user-avatar" src="{{ static_url }}/answer/img/avatar.png"><br>
                                        {% endif %}
                                            <span>修改头像：</span><input id="id_avatar" name="avatar" type="file">
                                        {% if user_profile_form.errors %}
                                            <label class="width-8 block" >[用户名]<span class="error margin-l-10">{% if user_profile_form.errors.username %}{{ user_profile_form.errors.username }}{% endif %}</span></label>
                                            <label class="dark-bg white-text shadow-light width-98">{{ uinfo_dict.username }}</label><br> 
                                            <label class="width-8 block" >[个人简介]<span class="error margin-l-10">{% if user_profile_form.errors.description %}{{ user_profile_form.errors.description }}{% endif %}</span></label>
                                            <textarea maxlength=250 class="dark-bg white-text shadow-light width-98" name="description" placeholder="你做过的项目，你的人生信条，您的自白～～">{{ user_profile_form.cleaned_data.description }}</textarea><br>
                                            <label class="width-8 block" >[主页]<span class="error margin-l-10">{% if user_profile_form.errors.website %}{{ user_profile_form.errors.website }}{% endif %}</span></label>
                                            <input maxlength=250 value="{{ user_profile_form.cleaned_data.website }}" class="dark-bg white-text shadow-light width-98" name="website" placeholder="个人主页，项目主页"></input><br>
                                            <label class="width-8 block" >[擅长的领域]<span class="error margin-l-10">{% if user_profile_form.errors.goodat %}{{ user_profile_form.errors.goodat }}{% endif %}</span></label>
                                            <input maxlength=250 value="{{ user_profile_form.cleaned_data.good_at }}" class="dark-bg white-text shadow-light width-98" name="good_at" placeholder="填写擅长的领域方便大家交流"></input><br>
                                            <label class="width-8 block" >[感兴趣的领域]<span class="error margin-l-10">{% if user_profile_form.errors.interests %}{{ user_profile_form.errors.interests }}{% endif %}</span></label>
                                            <input maxlength=250 value="{{ user_profile_form.cleaned_data.interests }}"  class="dark-bg white-text shadow-light width-98" name="interests" placeholder="填写兴趣让大家更容易了解你"></input><br>
                                        {% else %}
                                            <label class="width-8 block" >[用户名]</label>
                                            <label class="dark-bg white-text shadow-light width-98">{{ uinfo_dict.username }}</label><br> 
                                            <label class="width-8 block" >[个人简介]</label>
                                            <textarea maxlength=250 class="dark-bg white-text shadow-light width-98" name="description" placeholder="你做过的项目，你的人生信条，您的自白～～">{{ uinfo_dict.description }}</textarea><br>
                                            <label class="width-8 block" >[主页]</label>
                                            <input maxlength=250 value="{{ uinfo_dict.website }}" class="dark-bg white-text shadow-light width-98" name="website" placeholder="个人主页，项目主页"></input><br>
                                            <label class="width-8 block" >[擅长的领域]</label>
                                            <input maxlength=250 value="{{ uinfo_dict.good_at }}" class="dark-bg white-text shadow-light width-98" name="good_at" placeholder="填写擅长的领域方便大家交流"></input><br>
                                            <label class="width-8 block" >[感兴趣的领域]</label>
                                            <input maxlength=250 value="{{ uinfo_dict.interests }}"  class="dark-bg white-text shadow-light width-98" name="interests" placeholder="填写兴趣让大家更容易了解你"></input><br>
                                        {% endif %}
                                        </div>
                                        <input type="submit" class="black-gray-btn no-border radius-3 padding-5-10 margin-t-20 shadow-light" value="保存修改"/>
                                        <a href="{{ answer_url }}gear/{{ uinfo_dict.id }}/profile/" class="black-gray-btn no-border radius-3 padding-5-10 margin-t-20 shadow-light">放弃修改并返回</a>
                                    </form>
                                </div><!--end a left-cell-->

                                <div class="left-cell font-11px border-bottom">
                                    <span>帮助：<a href="#">关于社区积分</a></span>
                                    <span class="right">&gt;&gt;&gt;<a href="{{ answer_url }}">{{ site_name }}</a></span>
                                </div><!--end a left-cell-->
                                
                            </div><!--end left-box-->
{% endblock left_box %}



{% block hot_post %}{% endblock %}
{% block new_nodes %}{% endblock %}
{% block hot_nodes %}{% endblock %} 

GearAnswer/templates/gearanswer/info.html
{% extends "gearanswer/base.html" %}
{% block title %}提示 | {{ site_name }}{% endblock %}
{% block left_box %}
                            <div class="left-box gray-bg reply-box radius-3 light-black-box-shadow ">
                                <div class="left-cell gray-text ">
                                    <strong>
                                        <a href="{{ answer_url }}" >{{ site_name }}</a>
                                        &gt; 
                                        提示
                                    </strong>
                                </div><!--end a left-cell-->
                            {% autoescape off %}
                                <div class="left-cell  text-center">
                                    <p><strong>{{ info.title }}</strong></p>
                                    <p>{{ info.content }}</p>
 
                                </div><!--end a left-cell-->
                            {% endautoescape %}
                            
                                <div class="left-cell font-11px border-bottom">
                                    <span>帮助：<a href="#">关于社区积分</a></span>
                                    <span class="right">&gt;&gt;&gt; <a href="{{ answer_url }}">GearAnswer</a></span>
                                </div><!--end a left-cell-->
                            
                            </div><!--end left-box-->
                        {% if info.redirect_url %}
                            <script language="javascript" type="text/javascript">
                                setInterval("redirect()", 2000);
                                function redirect()
                                {
                                    location.href = '{{ info.redirect_url }}';
                                }
                            </script>
                        {% endif %}
{% endblock left_box %}

{% block user %}{% endblock %}

{% block site_echo %}{% endblock %}
{% block hot_post %}{% endblock %}
{% block new_nodes %}{% endblock %}
{% block hot_nodes %}{% endblock %} 
 

GearAnswer/templates/gearanswer/login.html
{% extends "gearanswer/base.html" %}
{% block title %}登录 | {{ site_name }}{% endblock %}
{% block left_box %}
                            <div class="left-box gray-bg reply-box radius-3 light-black-box-shadow ">
                                <div class="left-cell gray-text ">
                                    <strong>
                                        <a href="{{ answer_url }}" >{{ site_name }}</a>
                                        &gt; 
                                        登录
                                    </strong>
                                </div><!--end a left-cell-->

                                <div class="left-cell font-11px">
                                    <form id="reply-to" action="" method="POST">
                                        <div class=" padding-bottom-5">
                                            {% csrf_token %}
                                            <label class="width-8 block">&gt;&gt;&gt;<span class="error margin-l-10">{% if login_form.errors.username %}{{ login_form.errors.username }}{% endif %}</span></label>
                                            <input value="{{ login_form.cleaned_data.username }}" required type="text" class="dark-bg white-text shadow-light width-98" name="username" placeholder="键入您的用户名" maxlength="250"></input><br>
                                            <label class="width-8 block">&gt;&gt;&gt;密码<span class="error margin-l-10">{% if login_form.errors.password %}{{ login_form.errors.password }}{% endif %}</span></label>
                                            <input required type="password" class="dark-bg white-text shadow-light width-98" name="password" placeholder="键入您的密码" maxlength="20"></input><br>
                                        </div>
                                        <input type="submit" class="black-gray-btn no-border radius-3 padding-5-10 margin-t-20 shadow-light" value="现在登录"/>
                                    </form>
                                </div><!--end a left-cell-->
                                <div class="left-cell font-11px border-bottom">
                                    <span>帮助：<a href="#">关于社区积分</a></span>
                                    <span class="right">&gt;&gt;&gt;<a href="{{ answer_url }}">{{ site_name }}</a></span>
                                </div><!--end a left-cell-->
                                
                            </div><!--end left-box-->
{% endblock left_box %}
{% block login %}{% endblock %}
{% block user %}{% endblock %}

{% block site_echo %}{% endblock %}
{% block hot_post %}{% endblock %}
{% block new_nodes %}{% endblock %}
{% block hot_nodes %}{% endblock %} 

GearAnswer/templates/gearanswer/new_topic.html
{% extends "gearanswer/node.html" %}
{% block top_nav %}{% endblock %}

GearAnswer/templates/gearanswer/register.html
{% extends "gearanswer/base.html" %}
{% block left_box %}
                            <div class="left-box gray-bg reply-box radius-3 light-black-box-shadow ">
                                <div class="left-cell gray-text ">
                                    <strong>
                                        <a href="#" >GearAnswer</a>
                                        > 
                                        注册
                                    </strong>
                                </div><!--end a left-cell-->

                                <div class="left-cell font-11px">
                                    <form id="reply-to" action="" method="POST">
                                        <div class=" padding-bottom-5">
                                            {% csrf_token %}
                                            <label class="width-8 block">>>>用户名<span class="error margin-l-10">{% if register_form.errors %}{{ register_form.errors.username }}{% endif %}</span></label>
                                            <input value="{{ register_form.cleaned_data.username }}" required type="text" class="dark-bg white-text shadow-light width-98" name="username" placeholder="键入您的用户名,长度不能超过125字符"></input><br>
                                            <label class="width-8 block">>>>密码</label>
                                            <input required type="password" class="dark-bg white-text shadow-light width-98" name="password1" placeholder="请保持较高复杂度"></input><br>
                                            <label required class="width-8 block">>>>再次输入密码<span class="error margin-l-10">{% if register_form.errors.password2 %}{{ register_form.errors.password2 }}{% endif %}</span></label>
                                            <input type="password" class="dark-bg white-text shadow-light width-98" name="password2" placeholder="确认密码"></input><br>
                                            <label class="width-8 block" >>>>E-Mail<span class="error margin-l-10">{% if register_form.errors.email %}{{ register_form.errors.email }}{% endif %}</span></label>
                                            <input value="{{ register_form.cleaned_data.email }}" required type="email" pattern="\w*?@\w*?\.\w*?" autocomplete="on" class="dark-bg white-text shadow-light width-98" name="email" placeholder="电子邮箱是恢复密码的唯一手段"></input><br>
                            
                                        </div>
                                        <input type="submit" class="black-gray-btn no-border radius-3 padding-5-10 margin-t-20 shadow-light" value="注册"/>
                                    </form>
                                </div><!--end a left-cell-->
                                <div class="left-cell font-11px border-bottom">
                                    <span>帮助：<a href="#">关于社区积分</a></span>
                                    <span class="right">>>>返回<a href="/">GearAnswer</a></span>
                                </div><!--end a left-cell-->
                                
                            </div><!--end left-box-->
{% endblock left_box %}

{% block user %}{% endblock %}

{% block site_echo %}{% endblock %}
{% block hot_post %}{% endblock %}
{% block new_nodes %}{% endblock %}
{% block hot_nodes %}{% endblock %} 
 